### ISSUE TITLE
Cannot build on 11.1-STABLE

### ISSUE THREAD

**Issue by bsiege** [badfilemagic/bsd-rngd#1]
Hi,
sorry, but cannot fix this myself. Tried with and without -DHARDENEDBSD 

```
~/bsd-rngd/bsd-rngd] # cc -v
FreeBSD clang version 5.0.1 (tags/RELEASE_501/final 320880) (based on LLVM 5.0.1)
Target: x86_64-unknown-freebsd11.1
Thread model: posix
InstalledDir: /usr/bin
uname -a
FreeBSD myserver 11.1-STABLE FreeBSD 11.1-STABLE #3 r328170: Sat Jan 20 05:13:36 CET 2018     root@myserver:/usr/obj/usr/src/sys/ATOMIC  amd64
```

```
# make
cc  -Wall -g -DHARDENEDBSD -O2 bsdrngd.c -o bsdrngd
bsdrngd.c:278:60: warning: format specifies type 'unsigned int' but the argument has type 'unsigned int (*)(unsigned int)' [-Wformat]
                        errx(1, "Sleep seconds is out of range (0,10): %u: %s", sleep, errstr);
                                                                       ~~       ^~~~~
bsdrngd.c:283:88: warning: format specifies type 'int' but the argument has type 'unsigned int (*)(unsigned int)' [-Wformat]
                        syslog(LOG_ERR, "Specified value for sleep interval %d is out of range (0,10): %s", sleep, errstr);
                                                                            ~~                              ^~~~~
2 warnings generated.
/tmp/bsdrngd-c77cfe.o: In function 'main':
/root/bsd-rngd/bsd-rngd/bsdrngd.c:287: undefined reference to pidfile_open
/root/bsd-rngd/bsd-rngd/bsdrngd.c:300: undefined reference to pidfile_write
/root/bsd-rngd/bsd-rngd/bsdrngd.c:304: undefined reference to pidfile_remove
/root/bsd-rngd/bsd-rngd/bsdrngd.c:296: undefined reference to pidfile_remove
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make: stopped in /root/bsd-rngd/bsd-rngd
```

regards

**Comment by badfilemagic** [comment]
I just noticed this today... I apologize that it has been so long.

That bug was from forgetting to actually link to libutil in the Makefile in the version that was pushed up.  I also found a couple of other things while I was revisiting this code.  You should find now that it builds (on FreeBSD 12.0-RELEASE)
